algoritmo "exercicio2"
// Função :
// Autor :
// Data : 10/03/2020
// Seção de Declarações 
var
   base, altura, area, perimetro: real
inicio
// Seção de Comandos
   escreva ("Digite a base: ")
   leia (base)
   escreva ("Digite a altura: ")
   leia (altura)
   area <- base * altura
   escreval ("a area do retangulo eh", area)
   perimetro <-  (base*2) + (altura*2)
   escreva ("o perimetro do retangulo eh", perimetro)
fimalgoritmo
