algoritmo "aula06 - exercicio02"
// Função :
// Autor :
// Data : 07/04/2020
// Seção de Declarações 
var
contador, n1, n2, resultado:inteiro
inicio
// Seção de Comandos
escreval("digite o valor do primeiro número: ")
leia(n1)
escreval("digite o valor do segundo número: ")
leia(n2)
resultado <- 0
para contador de 1 ate n1 passo 1 faca
resultado <- resultado + n2
fimpara
escreval(n1, " x", n2, " =", resultado )
fimalgoritmo
